server:
  port: 8080

spring:
  config:
    import: "optional:file:../.env[.properties]"
  datasource:
    # url: jdbc:postgresql://db.uhquhfxirazgkkveoclz.supabase.co:5432/postgres?user=postgres&password=LYRVmjwNIh4WZHfj
    # dns for college:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.uhquhfxirazgkkveoclz
    password: LYRVmjwNIh4WZHfj
    hikari:
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0
        preparedStatementCacheSize: 0
    # url: jdbc:postgresql://ep-withered-cherry-ah0gdbwj-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_OSf4jIh9QYde&sslmode=require&channelBinding=require
    # username: neondb_owner
    # password: npg_OSf4jIh9QYde
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

supabase:
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  storage-bucket: restaurant-logos
  menu-items-bucket: menu_items

app:
  qr-base-url: ${QR_BASE_URL:https://menux-new.vercel.app}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://menux-new.vercel.app}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
